pub struct Uid(u64);
impl Default for Uid {
    fn default() -> Uid {
        Uid(501)
    }
}
impl Into<u64> for Uid {
    fn into(self) -> u64 {
        self.0
    }
}
impl From<u64> for Uid {
    fn from(u: u64) -> Uid {
        Uid(u)
    }
}
impl From<Option<u64>> for Uid {
    fn from(u: Option<u64>) -> Uid {
        match u {
            Some(u) => Uid(u),
            None => Uid::default(),
        }
    }
}
impl From<i32> for Uid {
    fn from(u: i32) -> Uid {
        Uid(u as u64)
    }
}
impl Copy for Uid {}
impl Clone for Uid {
    fn clone(&self) -> Uid {
        Uid(self.0)
    }
}
impl std::str::FromStr for Uid {
    type Err = crate::Error;

    fn from_str(s: &str) -> Result<Uid, crate::Error> {
        Ok(Uid(u64::from_str_radix(s, 10)?))
    }
}
impl std::fmt::Display for Uid {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}
impl std::fmt::Debug for Uid {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "Uid({})", self.0)
    }
}
impl From<u32> for Uid {
    fn from(u: u32) -> Uid {
        Uid(u as u64)
    }
}

pub fn list_agents_and_daemons(
    uid: Option<Uid>,
    with_qualifier: bool,
    user: bool,
    gui: bool,
    library: bool,
    system: bool,
    quiet: bool,
) -> crate::Result<Vec<String>> {
    let uid = uid.unwrap_or_default();
    use iocore::Path;
    let mut agents_and_daemons = Vec::<String>::new();

    for path in list_agents_and_daemons_paths(user, library, system)? {
        let prefix = if path.to_string().starts_with("/System") {
            format!("system")
        } else if gui {
            format!("gui/{}", &uid)
        } else {
            format!("user/{}", &uid)
        };
        let label = match determine_agent_or_daemon_label(&Path::raw(&path)) {
            Ok(label) => label,
            Err(error) => {
                if !quiet {
                    eprintln!("\x1b[1;38;5;220m{} skipped: {}\x1b[0m", &path, error.to_string());
                }
                continue;
            },
        };
        if with_qualifier {
            agents_and_daemons.push(format!("{}/{}", prefix, label));
        } else {
            agents_and_daemons.push(label);
        }
    }
    Ok(agents_and_daemons)
}

pub fn list_agents_and_daemons_paths(
    user: bool,
    library: bool,
    system: bool,
) -> crate::Result<Vec<iocore::Path>> {
    use iocore::Path;
    let mut agents_and_daemons_paths = Vec::<Path>::new();
    let mut search_paths = Vec::<Path>::new();
    if user {
        search_paths.push(Path::new("~/Library/LaunchAgents"));
        search_paths.push(Path::new("~/Library/LaunchDaemons"));
    }
    if library {
        search_paths.push(Path::new("/Library/LaunchAgents"));
        search_paths.push(Path::new("/Library/LaunchDaemons"));
    }
    if system {
        search_paths.push(Path::new("/System/Library/LaunchAgents"));
        search_paths.push(Path::new("/System/Library/LaunchDaemons"));
    }

    for path in search_paths {
        for agent_or_daemon_path in path.list()? {
            if let Some(extension) = agent_or_daemon_path.extension() {
                if extension == ".plist" {
                    agents_and_daemons_paths.push(agent_or_daemon_path.clone());
                }
            }
        }
    }
    Ok(agents_and_daemons_paths)
}

pub fn plist_from_agent_or_daemon_path(
    agent_or_daemon_path: &iocore::Path,
) -> crate::Result<plist::Dictionary> {
    use plist::{from_file, Dictionary};
    return Ok(from_file::<std::path::PathBuf, Dictionary>(
        agent_or_daemon_path.to_path_buf(),
    )?);
}
pub fn label_from_plist(dictionary: &plist::Dictionary) -> Option<String> {
    use plist::Value;
    match dictionary.get("Label") {
        Some(Value::String(label)) => Some(label.to_string()),
        _ => None,
    }
}
pub fn determine_agent_or_daemon_label(
    agent_or_daemon_path: &iocore::Path,
) -> crate::Result<String> {
    let fallback_label = agent_or_daemon_path.without_extension().name();
    let dictionary = plist_from_agent_or_daemon_path(agent_or_daemon_path)?;
    Ok(label_from_plist(&dictionary).unwrap_or_else(|| fallback_label))
}

pub fn system_uids() -> Vec<Option<Uid>> {
    [
        Uid(0),   // root
        Uid(55),  // _appleevents - Apple Events
        Uid(88),  // _windowserver - WindowServer
        Uid(89),  // _spotlight - Spotlight
        Uid(200), // _softwareupdate - Software Update Service
        Uid(202), // _coreaudiod - Core Audio Daemon
        Uid(205), // _locationd - Location Daemon
        Uid(242), // _nsurlsessiond - NSURLSession Daemon
        Uid(262), // _cmiodalassistants - CoreMedia IO Assistants User
    ]
    .iter()
    .map(|uid| Some(uid.clone()))
    .collect::<Vec<Option<Uid>>>()
}

pub fn agents_and_daemons_path_map(
    user: bool,
    library: bool,
    system: bool,
) -> crate::Result<std::collections::BTreeMap<String, (iocore::Path, plist::Dictionary)>> {
    let mut map = std::collections::BTreeMap::<String, (iocore::Path, plist::Dictionary)>::new();
    for path in list_agents_and_daemons_paths(user, library, system)? {
        let fallback_label = path.without_extension().name();
        let dictionary = plist_from_agent_or_daemon_path(&path)?;
        let label = label_from_plist(&dictionary).unwrap_or_else(|| fallback_label);
        map.insert(label, (path.clone(), dictionary));
    }
    Ok(map)
}

#[cfg(test)]
mod tests {
    use crate::{agents_and_daemons_path_map, Result};
    #[test]
    fn test_agents_and_daemons_path_map_system() -> Result<()> {
        let map = agents_and_daemons_path_map(false, false, true)?;

        assert_eq!(
            map.keys().map(|j| j.to_string()).collect::<Vec<String>>(),
            vec![
                "com.apple.AEServer",
                "com.apple.AMPArtworkAgent",
                "com.apple.AMPDeviceDiscoveryAgent",
                "com.apple.AMPDevicesAgent",
                "com.apple.AMPLibraryAgent",
                "com.apple.AMPSystemPlayerAgent",
                "com.apple.AOSHeartbeat",
                "com.apple.AOSPushRelay",
                "com.apple.ATS.FontValidator",
                "com.apple.AccessibilityVisualsAgent",
                "com.apple.AddressBook.AssistantService",
                "com.apple.AddressBook.SourceSync",
                "com.apple.AddressBook.abd",
                "com.apple.AirPlayUIAgent",
                "com.apple.AirPlayXPCHelper",
                "com.apple.AirPortBaseStationAgent",
                "com.apple.AppSSOAgent",
                "com.apple.AppSSOAgent.login",
                "com.apple.AppSSODaemon",
                "com.apple.AppleCredentialManagerDaemon",
                "com.apple.AppleQEMUGuestAgent",
                "com.apple.AquaAppearanceHelper",
                "com.apple.AskPermissionUI",
                "com.apple.AssetCache.agent",
                "com.apple.AssetCache.builtin",
                "com.apple.AssetCacheLocatorService",
                "com.apple.AssetCacheManagerService",
                "com.apple.AssetCacheTetheratorService",
                "com.apple.AssistiveControl",
                "com.apple.AuthenticationServicesCore.AuthenticationServicesAgent",
                "com.apple.AutoFillPanel",
                "com.apple.BTServer.cloudpairing",
                "com.apple.BTServer.le",
                "com.apple.BTServer.le.agent",
                "com.apple.BiomeAgent",
                "com.apple.BlueTool",
                "com.apple.BluetoothUIService",
                "com.apple.CSCSupportd",
                "com.apple.CallHistoryPluginHelper",
                "com.apple.CallHistorySyncHelper",
                "com.apple.CommCenter",
                "com.apple.ContainerMigrationService",
                "com.apple.ContextStoreAgent",
                "com.apple.CoreAuthentication.agent",
                "com.apple.CoreAuthentication.daemon",
                "com.apple.CoreLocationAgent",
                "com.apple.CrashReporterSupportHelper",
                "com.apple.CryptoTokenKit.ahp",
                "com.apple.CryptoTokenKit.ahp.agent",
                "com.apple.DataDetectorsLocalSources",
                "com.apple.DataDetectorsSourceAccess",
                "com.apple.DesktopServicesHelper",
                "com.apple.DiagnosticsReporter",
                "com.apple.DictationIM",
                "com.apple.DiskArbitrationAgent",
                "com.apple.Dock.agent",
                "com.apple.DumpGPURestart",
                "com.apple.DumpPanic",
                "com.apple.DumpPanic.Accessory",
                "com.apple.DwellControl",
                "com.apple.EscrowSecurityAlert",
                "com.apple.ExpansionSlotNotification",
                "com.apple.FamilyControlsAgent",
                "com.apple.FileCoordination",
                "com.apple.FileProvider",
                "com.apple.FilesystemUI",
                "com.apple.Finder",
                "com.apple.FolderActionsDispatcher",
                "com.apple.FollowUpUI",
                "com.apple.FontRegistryUIAgent",
                "com.apple.FontWorker",
                "com.apple.GSSCred",
                "com.apple.GameController.gamecontrolleragentd",
                "com.apple.GameController.gamecontrollerd",
                "com.apple.GamePolicyAgent",
                "com.apple.IFCStart",
                "com.apple.IOAccelMemoryInfoCollector",
                "com.apple.IOUIAgent",
                "com.apple.InstallerDiagnostics.installerdiagd",
                "com.apple.InstallerDiagnostics.installerdiagwatcher",
                "com.apple.InstallerProgress",
                "com.apple.Kerberos.digest-service",
                "com.apple.Kerberos.kadmind",
                "com.apple.Kerberos.kcm",
                "com.apple.Kerberos.kdc",
                "com.apple.Kerberos.kpasswdd",
                "com.apple.KernelEventAgent",
                "com.apple.KeyboardAccessAgent",
                "com.apple.LinkedNotesUIService",
                "com.apple.LocalAuthentication.UIAgent",
                "com.apple.MENotificationService",
                "com.apple.MTLAssetUpgraderD",
                "com.apple.ManagedClient",
                "com.apple.ManagedClient.cloudconfigurationd",
                "com.apple.ManagedClient.enroll",
                "com.apple.ManagedClient.mechanism",
                "com.apple.ManagedClient.startup",
                "com.apple.ManagedClientAgent.agent",
                "com.apple.ManagedClientAgent.enrollagent",
                "com.apple.ManagedSettingsAgent",
                "com.apple.Maps.mapspushd",
                "com.apple.Maps.mapssyncd",
                "com.apple.MemorySlotNotification",
                "com.apple.MobileAccessoryUpdater.fudHelperAgent",
                "com.apple.MobileFileIntegrity",
                "com.apple.NVMeAgent",
                "com.apple.NetworkSharing",
                "com.apple.ODSAgent",
                "com.apple.OSDUIHelper",
                "com.apple.PIPAgent",
                "com.apple.PackageUIKit.InstallStatus",
                "com.apple.PasswordService",
                "com.apple.PerfPowerServices",
                "com.apple.PerfPowerServicesExtended",
                "com.apple.PowerUIAgent",
                "com.apple.RFBEventHelper",
                "com.apple.RapportUIAgent",
                "com.apple.RemoteDesktop.PrivilegeProxy",
                "com.apple.RemoteDesktop.agent",
                "com.apple.RemoteManagementAgent",
                "com.apple.RemotePairTool",
                "com.apple.ReportCrash",
                "com.apple.ReportCrash.Root",
                "com.apple.ReportGPURestart",
                "com.apple.ReportMemoryException",
                "com.apple.ReportSystemMemory",
                "com.apple.SCHelper",
                "com.apple.STMUIHelper",
                "com.apple.Safari.History",
                "com.apple.Safari.PasswordBreachAgent",
                "com.apple.Safari.SafeBrowsing.Service",
                "com.apple.SafariBookmarksSyncAgent",
                "com.apple.SafariHistoryServiceAgent",
                "com.apple.SafariLaunchAgent",
                "com.apple.SafariNotificationAgent",
                "com.apple.SafeEjectGPUAgent",
                "com.apple.SafeEjectGPUStartupDaemon",
                "com.apple.ScreenReaderUIServer",
                "com.apple.ScreenTimeAgent",
                "com.apple.ScriptMenuApp",
                "com.apple.SecureBackupDaemon",
                "com.apple.ServicesUIAgent",
                "com.apple.Siri.agent",
                "com.apple.SiriTTSTrainingAgent",
                "com.apple.SoftwareUpdateNotificationManager",
                "com.apple.SpacesTouchBarAgent.app",
                "com.apple.Spotlight",
                "com.apple.StatusKitAgent",
                "com.apple.StorageManagement.Service",
                "com.apple.SubmitDiagInfo",
                "com.apple.SystemUIServer.agent",
                "com.apple.TMHelperAgent",
                "com.apple.TextInputMenuAgent",
                "com.apple.TextInputSwitcher",
                "com.apple.ThreadCommissionerService",
                "com.apple.TrustEvaluationAgent",
                "com.apple.TrustEvaluationAgent.system",
                "com.apple.USBAgent",
                "com.apple.UpdateSettings",
                "com.apple.UsageTrackingAgent",
                "com.apple.UserEventAgent-Aqua",
                "com.apple.UserEventAgent-CryptexContainer",
                "com.apple.UserEventAgent-LoginWindow",
                "com.apple.UserEventAgent-System",
                "com.apple.UserNotificationCenter",
                "com.apple.UserNotificationCenterAgent",
                "com.apple.UserNotificationCenterAgent-LoginWindow",
                "com.apple.UserPictureSyncAgent",
                "com.apple.Virtualization.AppleVirtualPlatformHIDBridge",
                "com.apple.VoiceOver",
                "com.apple.WindowManager.agent",
                "com.apple.WindowServer",
                "com.apple.WirelessRadioManager",
                "com.apple.accessibility.AXVisualSupportAgent",
                "com.apple.accessibility.LiveTranscriptionAgent",
                "com.apple.accessibility.MotionTrackingAgent",
                "com.apple.accessibility.axassetsd",
                "com.apple.accessibility.dfrhud",
                "com.apple.accessibility.heard",
                "com.apple.accessoryd",
                "com.apple.accessoryupdaterd",
                "com.apple.accountsd",
                "com.apple.adid",
                "com.apple.afpfs_afpLoad",
                "com.apple.afpfs_checkafp",
                "com.apple.airport.wps",
                "com.apple.airportd",
                "com.apple.akd",
                "com.apple.alf",
                "com.apple.alf.useragent",
                "com.apple.amp.mediasharingd",
                "com.apple.amsaccountsd",
                "com.apple.amsengagementd",
                "com.apple.analyticsd",
                "com.apple.aned",
                "com.apple.aneuserd",
                "com.apple.aonsensed",
                "com.apple.ap.adprivacyd",
                "com.apple.ap.promotedcontentd",
                "com.apple.apfsd",
                "com.apple.apfsuseragent",
                "com.apple.appinstalld",
                "com.apple.appleaccountd",
                "com.apple.appleh13camerad",
                "com.apple.appleh16camerad",
                "com.apple.appleidsetupd",
                "com.apple.applekeystored",
                "com.apple.appleseed.fbahelperd",
                "com.apple.appleseed.seedusaged",
                "com.apple.appleseed.seedusaged.postinstall",
                "com.apple.applespell",
                "com.apple.applessdstatistics",
                "com.apple.appplaceholdersyncd",
                "com.apple.appsleep",
                "com.apple.appstoreagent",
                "com.apple.appstorecomponentsd",
                "com.apple.appstored",
                "com.apple.apsd",
                "com.apple.askpermissiond",
                "com.apple.asktod",
                "com.apple.aslmanager",
                "com.apple.asr",
                "com.apple.assessmentagent",
                "com.apple.assistant_cdmd",
                "com.apple.assistant_service",
                "com.apple.assistantd",
                "com.apple.atrun",
                "com.apple.atsd",
                "com.apple.attentionawarenessd",
                "com.apple.audio.AudioComponentRegistrar",
                "com.apple.audio.coreaudiod",
                "com.apple.audio.systemsoundserverd",
                "com.apple.audioanalyticsd",
                "com.apple.audiomxd",
                "com.apple.auditd",
                "com.apple.autofsd",
                "com.apple.automountd",
                "com.apple.avatarsd",
                "com.apple.avbdeviced",
                "com.apple.awdd",
                "com.apple.backgroundassets.user",
                "com.apple.backgroundtaskmanagement.agent",
                "com.apple.backgroundtaskmanagementd",
                "com.apple.backupd",
                "com.apple.backupd-helper",
                "com.apple.betaenrollmentd",
                "com.apple.biomed",
                "com.apple.biomesyncd",
                "com.apple.biometrickitd",
                "com.apple.bird",
                "com.apple.bluetoothUIServer",
                "com.apple.bluetoothd",
                "com.apple.bluetoothuserd",
                "com.apple.bookassetd",
                "com.apple.bookdatastored",
                "com.apple.bootinstalld",
                "com.apple.bootpd",
                "com.apple.bosreporter",
                "com.apple.boswatcher",
                "com.apple.bridgeOSUpdateProxy",
                "com.apple.bsd.dirhelper",
                "com.apple.btsa",
                "com.apple.businessservicesd",
                "com.apple.cache_delete",
                "com.apple.calaccessd",
                "com.apple.calendar.CalendarAgentBookmarkMigrationService",
                "com.apple.cameracaptured",
                "com.apple.captiveagent",
                "com.apple.cdpd",
                "com.apple.cfnetwork.AuthBrokerAgent",
                "com.apple.cfnetwork.cfnetworkagent",
                "com.apple.cfprefsd.xpc.agent",
                "com.apple.cfprefsd.xpc.daemon",
                "com.apple.chronod",
                "com.apple.ciphermld",
                "com.apple.ckdiscretionaryd",
                "com.apple.cloudd",
                "com.apple.cloudphotod",
                "com.apple.cloudsettingssyncagent",
                "com.apple.cmfsyncagent",
                "com.apple.cmio.AVCAssistant",
                "com.apple.cmio.ContinuityCaptureAgent",
                "com.apple.cmio.IIDCVideoAssistant",
                "com.apple.cmio.LaunchCMIOUserExtensionsAgent",
                "com.apple.cmio.VDCAssistant",
                "com.apple.cmio.iOSScreenCaptureAssistant",
                "com.apple.cmio.registerassistantservice",
                "com.apple.cmio.uvcassistantextension",
                "com.apple.colorsync.displayservices",
                "com.apple.colorsync.useragent",
                "com.apple.colorsyncd",
                "com.apple.commerce",
                "com.apple.companiond",
                "com.apple.configd",
                "com.apple.configureLocalKDC",
                "com.apple.contacts.donation-agent",
                "com.apple.contactsd",
                "com.apple.containermanagerd",
                "com.apple.containermanagerd.system",
                "com.apple.contextstored",
                "com.apple.controlcenter",
                "com.apple.controlstrip",
                "com.apple.coordinated",
                "com.apple.corebrightnessd",
                "com.apple.corecaptured",
                "com.apple.coredatad",
                "com.apple.coreduetd",
                "com.apple.coreimportd",
                "com.apple.corekdld",
                "com.apple.corercd",
                "com.apple.coreservices.UASharedPasteboardProgressUI",
                "com.apple.coreservices.appleevents",
                "com.apple.coreservices.launchservicesd",
                "com.apple.coreservices.sharedfilelistd",
                "com.apple.coreservices.uiagent",
                "com.apple.coreservices.useractivityd",
                "com.apple.coreservicesd",
                "com.apple.corespeechd",
                "com.apple.corespotlightd",
                "com.apple.corespotlightservice",
                "com.apple.corestorage.corestoraged",
                "com.apple.corestorage.corestoragehelperd",
                "com.apple.coresymbolicationd",
                "com.apple.countryd",
                "com.apple.csrutil.report",
                "com.apple.csuseragent",
                "com.apple.ctkbind",
                "com.apple.ctkd",
                "com.apple.cvmsCompAgent3425AMD_x86_64",
                "com.apple.cvmsCompAgent3425AMD_x86_64_1",
                "com.apple.cvmsCompAgent3600_arm64",
                "com.apple.cvmsCompAgent3600_arm64_1",
                "com.apple.cvmsCompAgent3600_x86_64",
                "com.apple.cvmsCompAgent3600_x86_64_1",
                "com.apple.cvmsCompAgent_arm64",
                "com.apple.cvmsCompAgent_arm64_1",
                "com.apple.cvmsCompAgent_x86_64",
                "com.apple.cvmsCompAgent_x86_64_1",
                "com.apple.cvmsServ",
                "com.apple.dasd",
                "com.apple.dataaccess.dataaccessd",
                "com.apple.datastored",
                "com.apple.deleted_helper",
                "com.apple.devicecheckd",
                "com.apple.devicemanagementclient.managedeventsd",
                "com.apple.devicemanagementclient.teslad",
                "com.apple.dhcp6d",
                "com.apple.diagnosticd",
                "com.apple.diagnosticextensions.osx.spotlight.helper",
                "com.apple.diagnosticextensions.osx.timemachine.helper",
                "com.apple.diagnosticextensionsd",
                "com.apple.diagnostics_agent",
                "com.apple.diskarbitrationd",
                "com.apple.diskimagesiod",
                "com.apple.diskimagesiod.ram",
                "com.apple.diskimagesiod.spb",
                "com.apple.diskmanagementstartup",
                "com.apple.diskspaced",
                "com.apple.displaypolicyd",
                "com.apple.distnoted.xpc.agent",
                "com.apple.distnoted.xpc.daemon",
                "com.apple.dmd",
                "com.apple.donotdisturbd",
                "com.apple.dprivacyd",
                "com.apple.dspluginhelperd",
                "com.apple.dt.AutomationModeUI",
                "com.apple.dt.CommandLineTools.installondemand",
                "com.apple.dt.automationmode-writer",
                "com.apple.dt.fetchsymbolsd",
                "com.apple.duetexpertd",
                "com.apple.dvdplayback.setregion",
                "com.apple.dynamic_pager",
                "com.apple.eapolcfg_auth",
                "com.apple.ecosystemanalyticsd",
                "com.apple.efilogin-helper",
                "com.apple.eligibilityd",
                "com.apple.email.maild",
                "com.apple.endpointsecurity.endpointsecurityd",
                "com.apple.ensemble",
                "com.apple.eoshostd",
                "com.apple.erasecontentsettingshelperd",
                "com.apple.exchange.exchangesyncd",
                "com.apple.fairplayd",
                "com.apple.fairplaydeviceidentityd",
                "com.apple.familycircled",
                "com.apple.familycontrols",
                "com.apple.familycontrols.useragent",
                "com.apple.familynotificationd",
                "com.apple.feedbackd",
                "com.apple.filesystems.doubleagentd",
                "com.apple.filesystems.fskitd",
                "com.apple.filesystems.userfs_helper",
                "com.apple.filesystems.userfsd",
                "com.apple.financed",
                "com.apple.findmy.findmybeaconingd",
                "com.apple.findmy.findmylocateagent",
                "com.apple.findmymacd",
                "com.apple.findmymacmessenger",
                "com.apple.firmwaresyncd",
                "com.apple.followupd",
                "com.apple.fontmover",
                "com.apple.fseventsd",
                "com.apple.fskit.fskit_agent",
                "com.apple.fskit.fskit_helper",
                "com.apple.ftp-proxy",
                "com.apple.gamed",
                "com.apple.gamepolicyd",
                "com.apple.generativeexperiencesd",
                "com.apple.geoanalyticsd",
                "com.apple.geodMachServiceBridge",
                "com.apple.getty",
                "com.apple.gkreport",
                "com.apple.gputoolsserviced",
                "com.apple.griddatad",
                "com.apple.gssd",
                "com.apple.handwritingd",
                "com.apple.hdiejectd",
                "com.apple.helpd",
                "com.apple.hidd",
                "com.apple.homed",
                "com.apple.homeenergyd",
                "com.apple.iCloudNotificationAgent",
                "com.apple.iCloudUserNotificationsd",
                "com.apple.icdd",
                "com.apple.icloud.findmydeviced",
                "com.apple.icloud.findmydeviced.findmydevice-user-agent",
                "com.apple.icloud.fmfd",
                "com.apple.icloud.searchpartyd",
                "com.apple.icloud.searchpartyuseragent",
                "com.apple.icloudmailagent",
                "com.apple.iconservices.iconservicesagent",
                "com.apple.iconservices.iconservicesd",
                "com.apple.identityservicesd",
                "com.apple.idleassetsd",
                "com.apple.idsfoundation.IDSRemoteURLConnectionAgent",
                "com.apple.ifdreader",
                "com.apple.imagent",
                "com.apple.imautomatichistorydeletionagent",
                "com.apple.imcore.imtransferagent",
                "com.apple.imklaunchagent",
                "com.apple.inputanalyticsd",
                "com.apple.installandsetup.migrationhelper.user",
                "com.apple.installandsetup.systemmigrationd",
                "com.apple.installcoordination_proxy",
                "com.apple.installcoordinationd",
                "com.apple.installd",
                "com.apple.installd.user",
                "com.apple.installerauthagent",
                "com.apple.intelligencecontextd",
                "com.apple.intelligenceflowd",
                "com.apple.intelligenceplatformd",
                "com.apple.intelligentroutingd",
                "com.apple.iomfb_bics_daemon",
                "com.apple.iomfb_fdr_loader",
                "com.apple.ionodecache",
                "com.apple.ioupsd",
                "com.apple.itunescloudd",
                "com.apple.jetsamproperties.Mac",
                "com.apple.kcgend",
                "com.apple.kcproxy",
                "com.apple.kdumpd",
                "com.apple.kernelmanager_helper",
                "com.apple.kernelmanagerd",
                "com.apple.keyboardservicesd",
                "com.apple.keychainsharingmessagingd",
                "com.apple.knowledge-agent",
                "com.apple.knowledgeconstructiond",
                "com.apple.kuncd",
                "com.apple.languageassetd",
                "com.apple.lightsoutmanagementd",
                "com.apple.linkd",
                "com.apple.liquiddetectiond",
                "com.apple.localizationswitcherd",
                "com.apple.locate",
                "com.apple.locationd",
                "com.apple.lockd",
                "com.apple.lockdownmoded",
                "com.apple.lockoutagent",
                "com.apple.logd",
                "com.apple.logd_helper",
                "com.apple.logd_reporter",
                "com.apple.logind",
                "com.apple.loginwindow",
                "com.apple.loginwindow.LWWeeklyMessageTracer",
                "com.apple.logkextloadsd",
                "com.apple.lsd",
                "com.apple.lskdd",
                "com.apple.mDNSResponder.reloaded",
                "com.apple.mDNSResponderHelper.reloaded",
                "com.apple.managedappdistributionagent",
                "com.apple.managedappdistributiond",
                "com.apple.managedcorespotlightd",
                "com.apple.maps.destinationd",
                "com.apple.mbbackgrounduseragent",
                "com.apple.mbfloagent",
                "com.apple.mbproximityhelper",
                "com.apple.mbsystemadministration",
                "com.apple.mbuseragent",
                "com.apple.mbusertrampoline",
                "com.apple.mdmclient.agent",
                "com.apple.mdmclient.daemon",
                "com.apple.mdmclient.daemon.runatboot",
                "com.apple.mdworker.mail",
                "com.apple.mdworker.shared",
                "com.apple.mdworker.single.arm64",
                "com.apple.mdworker.single.x86_64",
                "com.apple.mdworker.sizing",
                "com.apple.mediaanalysisd",
                "com.apple.mediaremoteagent",
                "com.apple.mediaremoted",
                "com.apple.mediastream.mstreamd",
                "com.apple.memory-maintenance",
                "com.apple.menuextra.battery.helper",
                "com.apple.metadata.mdbulkimport",
                "com.apple.metadata.mdflagwriter",
                "com.apple.metadata.mds",
                "com.apple.metadata.mds.index",
                "com.apple.metadata.mds.scan",
                "com.apple.metadata.mds.spindump",
                "com.apple.metadata.mdwrite",
                "com.apple.metrickitd",
                "com.apple.midiserver",
                "com.apple.milod",
                "com.apple.misagent",
                "com.apple.mlhostd",
                "com.apple.mlruntimed",
                "com.apple.mobile.NRDUpdated",
                "com.apple.mobile.keybagd",
                "com.apple.mobile.notification_proxy",
                "com.apple.mobile.obliteration",
                "com.apple.mobile.softwareupdated",
                "com.apple.mobile.storage_mounter",
                "com.apple.mobile.storage_mounter_proxy",
                "com.apple.mobile.usermanagerd",
                "com.apple.mobileactivationd",
                "com.apple.mobileassetd",
                "com.apple.mobilegestalt.xpc",
                "com.apple.mobiletimerd",
                "com.apple.modelcatalogd",
                "com.apple.modelmanagerd",
                "com.apple.msrpc.echosvc",
                "com.apple.msrpc.lsarpc",
                "com.apple.msrpc.mdssvc",
                "com.apple.msrpc.netlogon",
                "com.apple.msrpc.srvsvc",
                "com.apple.msrpc.wkssvc",
                "com.apple.multiversed",
                "com.apple.nand.aspcarry",
                "com.apple.nand_task_scheduler",
                "com.apple.naturallanguaged",
                "com.apple.navd",
                "com.apple.ndoagent",
                "com.apple.neagent",
                "com.apple.nearbyd",
                "com.apple.nehelper",
                "com.apple.nesessionmanager",
                "com.apple.netauth.sys.auth",
                "com.apple.netauth.sys.gui",
                "com.apple.netauth.user.auth",
                "com.apple.netauth.user.gui",
                "com.apple.netbiosd",
                "com.apple.networkserviceproxy",
                "com.apple.newsd",
                "com.apple.newsyslog",
                "com.apple.nexusd",
                "com.apple.nfcd",
                "com.apple.nfsconf",
                "com.apple.nfsd",
                "com.apple.nlcd",
                "com.apple.notes.exchangenotesd",
                "com.apple.noticeboard.agent",
                "com.apple.noticeboard.state",
                "com.apple.notificationcenterui.agent",
                "com.apple.notifyd",
                "com.apple.nowplayingtouchui",
                "com.apple.nsurlsessiond",
                "com.apple.nsurlsessiond_privileged",
                "com.apple.ntalkd",
                "com.apple.oahd",
                "com.apple.oahd-root-helper",
                "com.apple.ocspd",
                "com.apple.odproxyd",
                "com.apple.online-auth-agent.xpc",
                "com.apple.opendirectoryd",
                "com.apple.osanalytics.osanalyticshelper",
                "com.apple.ospredictiond",
                "com.apple.parentalcontrols.check",
                "com.apple.parsec-fbf",
                "com.apple.parsecd",
                "com.apple.passd",
                "com.apple.pboard",
                "com.apple.pbs",
                "com.apple.peopled",
                "com.apple.pfctl",
                "com.apple.pfd",
                "com.apple.photoanalysisd",
                "com.apple.photolibraryd",
                "com.apple.pluginkit.pkd",
                "com.apple.pluginkit.pkreporter",
                "com.apple.postfix.master",
                "com.apple.postfix.newaliases",
                "com.apple.powerchime",
                "com.apple.powerd",
                "com.apple.powerd.swd",
                "com.apple.powerdatad",
                "com.apple.powerexperienced",
                "com.apple.powerlogHelperd",
                "com.apple.preference.displays.MirrorDisplays",
                "com.apple.preferences.timezone.admintool",
                "com.apple.previewsd",
                "com.apple.previewshellapp",
                "com.apple.previewshellmacapp",
                "com.apple.printtool.agent",
                "com.apple.printtool.daemon",
                "com.apple.printuitool.agent",
                "com.apple.privatecloudcomputed",
                "com.apple.proactived",
                "com.apple.proactiveeventtrackerd",
                "com.apple.progressd",
                "com.apple.protectedcloudstorage.protectedcloudkeysyncing",
                "com.apple.ptpcamerad",
                "com.apple.quicklook",
                "com.apple.quicklook.ThumbnailsAgent",
                "com.apple.quicklook.ui.helper",
                "com.apple.racoon",
                "com.apple.rapportd",
                "com.apple.rcd",
                "com.apple.recentsd",
                "com.apple.relatived",
                "com.apple.remindd",
                "com.apple.remoted",
                "com.apple.remotemanagementd",
                "com.apple.replayd",
                "com.apple.replicatord",
                "com.apple.retimerd",
                "com.apple.reversetemplated",
                "com.apple.revisiond",
                "com.apple.routined",
                "com.apple.rpcbind",
                "com.apple.rtcreportingd",
                "com.apple.runningboardd",
                "com.apple.sandboxd",
                "com.apple.scopedbookmarksagent.xpc",
                "com.apple.screencaptureui.agent",
                "com.apple.screensharing",
                "com.apple.screensharing.MessagesAgent",
                "com.apple.screensharing.agent",
                "com.apple.screensharing.menuextra",
                "com.apple.scrod",
                "com.apple.scsid",
                "com.apple.secd",
                "com.apple.secinitd",
                "com.apple.security.DiskUnmountWatcher",
                "com.apple.security.FDERecoveryAgent",
                "com.apple.security.KeychainStasher",
                "com.apple.security.agent",
                "com.apple.security.agent.login",
                "com.apple.security.authhost",
                "com.apple.security.authtrampoline",
                "com.apple.security.cloudkeychainproxy3",
                "com.apple.security.cryptexd",
                "com.apple.security.keychain-circle-notification",
                "com.apple.security.syspolicy",
                "com.apple.securityd",
                "com.apple.securityd.system",
                "com.apple.securityuploadd",
                "com.apple.seld",
                "com.apple.seserviced",
                "com.apple.sessionlogoutd",
                "com.apple.sharingd",
                "com.apple.shazamd",
                "com.apple.sidecar-display-agent",
                "com.apple.sidecar-relay",
                "com.apple.signpost.signpost_reporter",
                "com.apple.siriactionsd",
                "com.apple.siriinferenced",
                "com.apple.siriknowledged",
                "com.apple.sirittsd",
                "com.apple.smb.preferences",
                "com.apple.smbd",
                "com.apple.sntpd",
                "com.apple.sociallayerd",
                "com.apple.softwareupdate_firstrun_tasks",
                "com.apple.softwareupdated",
                "com.apple.speech.speechdatainstallerd",
                "com.apple.speech.speechsynthesisd.arm64",
                "com.apple.speech.speechsynthesisd.x86_64",
                "com.apple.speech.synthesisserver",
                "com.apple.spindump",
                "com.apple.spindump_agent",
                "com.apple.sportsd",
                "com.apple.spotlightknowledged",
                "com.apple.spotlightknowledged.importer",
                "com.apple.spotlightknowledged.updater",
                "com.apple.srp-mdns-proxy",
                "com.apple.ssinvitationagent",
                "com.apple.startupdiskhelper",
                "com.apple.statd.notify",
                "com.apple.stickersd",
                "com.apple.storagekitd",
                "com.apple.storeaccountd",
                "com.apple.storeassetd",
                "com.apple.storedownloadd",
                "com.apple.storekitagent",
                "com.apple.storelegacy",
                "com.apple.storereceiptinstaller",
                "com.apple.storeuid",
                "com.apple.studentd",
                "com.apple.suggestd",
                "com.apple.suhelperd",
                "com.apple.swcd",
                "com.apple.swtransparencyd",
                "com.apple.symptomsd",
                "com.apple.symptomsd-diag",
                "com.apple.symptomsd-diag.agent",
                "com.apple.synapse.contentlinkingd",
                "com.apple.syncdefaultsd",
                "com.apple.syncservices.SyncServer",
                "com.apple.syncservices.uihandler",
                "com.apple.sysdiagnose",
                "com.apple.sysdiagnose_agent",
                "com.apple.sysdiagnose_helper",
                "com.apple.sysextd",
                "com.apple.syslogd",
                "com.apple.sysmond",
                "com.apple.system_installd",
                "com.apple.systemkeychain",
                "com.apple.systemprofiler",
                "com.apple.systemsettingsagent",
                "com.apple.systemstats.analysis",
                "com.apple.systemstats.daily",
                "com.apple.systemstats.microstackshot_periodic",
                "com.apple.systemstatusd",
                "com.apple.tailspind",
                "com.apple.talagent",
                "com.apple.taskgated",
                "com.apple.taskgated-helper",
                "com.apple.tccd",
                "com.apple.tccd.system",
                "com.apple.telephonyutilities.callservicesd",
                "com.apple.testmanagerd",
                "com.apple.testmanagerd.remote",
                "com.apple.textunderstandingd",
                "com.apple.tftpd",
                "com.apple.thermald",
                "com.apple.thermalmonitord",
                "com.apple.thermaltrap",
                "com.apple.threadradiod",
                "com.apple.timed",
                "com.apple.timesync.audioclocksyncd",
                "com.apple.timezoneupdates.tzd",
                "com.apple.timezoneupdates.tznotify",
                "com.apple.tipsd",
                "com.apple.tmp_cleaner",
                "com.apple.touchbarserver",
                "com.apple.tracd",
                "com.apple.translationd",
                "com.apple.transparencyStaticKey",
                "com.apple.transparencyd",
                "com.apple.triald",
                "com.apple.triald.system",
                "com.apple.trustd",
                "com.apple.trustd.agent",
                "com.apple.trustdFileHelper",
                "com.apple.tzlinkd",
                "com.apple.uarppersonalizationd",
                "com.apple.ucupdate.plist",
                "com.apple.uikitsystemapp",
                "com.apple.uninstalld",
                "com.apple.universalaccessAuthWarn",
                "com.apple.universalaccesscontrol",
                "com.apple.universalaccessd",
                "com.apple.unmountassistant.sysagent",
                "com.apple.unmountassistant.useragent",
                "com.apple.usbaudiod",
                "com.apple.usbctelemetryd",
                "com.apple.usbd",
                "com.apple.usbsmartcardreaderd",
                "com.apple.usermanagerhelper",
                "com.apple.usernoted",
                "com.apple.usernotificationsd",
                "com.apple.uucp",
                "com.apple.videoconference.camera",
                "com.apple.videosubscriptionsd",
                "com.apple.voicebankingd",
                "com.apple.voicememod",
                "com.apple.vsdbutil",
                "com.apple.wallpaper.agent",
                "com.apple.wallpaper.export",
                "com.apple.warmd",
                "com.apple.warmd_agent",
                "com.apple.watchdogd",
                "com.apple.watchlistd",
                "com.apple.weatherd",
                "com.apple.webinspectord",
                "com.apple.webkit.webpushd",
                "com.apple.webprivacyd",
                "com.apple.wifi.WiFiAgent",
                "com.apple.wifiFirmwareLoader",
                "com.apple.wifianalyticsd",
                "com.apple.wifip2pd",
                "com.apple.wifivelocityd",
                "com.apple.xartstorageremoted",
                "com.apple.xpc.loginitemregisterd",
                "com.apple.xpc.otherbsd",
                "com.apple.xpc.roleaccountd",
                "com.apple.xpc.smd",
                "com.apple.xpc.uscwoap",
                "com.apple.xsan",
                "com.apple.xscertadmin",
                "com.apple.xscertd",
                "com.apple.xscertd-helper",
                "com.apple.xtyped",
                "com.openssh.ssh-agent",
                "com.openssh.sshd",
                "com.vix.cron",
                "org.apache.httpd",
                "org.cups.cups-lpd",
                "org.cups.cupsd",
                "org.net-snmp.snmpd",
                "org.openldap.slapd"
            ]
        );
        Ok(())
    }
}
